### ISSUE TITLE
How to estimate the number of unknown classes.

### ISSUE THREAD

**Issue by jinweiisgreat** [deeplearning-wisc/opencon#4]
Thank you for your nice work. I am interesting about your work how to estimate the number of unknown classes. It seems like using prob cluster like DTC method, right? How can I find this part code? Thank you!

**Comment by sunyiyou** [comment]
Thanks for your interest in our work! Since the class number estimation is an independent module, our class number directly uses the one estimated in the ORCA paper which is 124 for C-100.
